=== sarah-blazic/terraform-panos-policy-as-code/examples/validate/schemas/anti_spyware_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "anti-spyware security profile json schema",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "name": {
        "type": "string",
        "maxLength": 127,
        "minLength": 1
      },
      "device_group": {
        "type": "string",
        "default": "shared",
        "maxLength": 31,
        "minLength": 1
      },
      "vsys": {
        "type": "string",
        "maxLength": 31,
        "minLength": 1,
        "default": "vsys1"
      },
      "description": {
        "type": "string",
        "maxLength": 255
      },
      "packet_capture": {
        "$ref": "#/$defs/capture_settings"
      },
      "sinkhole_ipv4_address": {
        "type": "string",
        "format": "ipv4"
      },
      "sinkhole_ipv6_address": {
        "type": "string",
        "format": "ipv6"
      },
      "threat_exceptions": {
        "type": "array",
        "items": {
          "type": "string"
        }
      },
      "botnet_list": {
        "type": "array",
        "items":
        {
          "type": "object",
          "properties": {
            "name": {
             "$ref": "#/$defs/naming"
            },
            "action": {
              "$ref": "#/$defs/actions_dns_botnet"
            },
            "packet_capture": {
              "$ref": "#/$defs/capture_settings"
            }
          },
          "additionalProperties": false,
          "required": [
            "name"
          ]
        }
      },
      "dns_category": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "type": "string",
              "maxLength": 31,
              "pattern": "^[a-zA-Z][a-zA-Z0-9_.\\s-]+$"
            },
            "action": {
              "$ref": "#/$defs/actions_dns_botnet"
            },
            "log_level": {
              "type": "string",
              "enum": ["default","none","low","informational","medium","high","critical"]
            },
            "packet_capture": {
              "$ref": "#/$defs/capture_settings"
            }
          },
          "additionalProperties": false,
          "required": [
            "name"
          ]
        }
      },
      "white_list": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "$ref": "#/$defs/naming"
            },
            "description": {
              "type": "string",
              "maxLength": 255

            }
          },
          "additionalProperties": false,
          "required": [
            "name"
          ]
        }
      },
      "rule": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "$ref": "#/$defs/naming"
            },
            "threat_name": {
              "type": "string",
              "default": "any",
              "maxLength": 255
            },
            "category": {
              "$ref": "#/$defs/categories"
            },
            "severities": {
              "type": "array",
              "default": ["any"],
              "items": {
                "type": "string",
                "enum": ["any","critical","high","medium","low","informational"]
              },
              "additionalItems": false
            },
            "packet_capture": {
              "$ref": "#/$defs/capture_settings"
            },
            "action": {
              "$ref": "#/$defs/actions_rule_except"
            },
            "block_ip_track_by": {
              "type": "string",
              "enum": ["source","source-and-destination"]
            },
            "block_ip_duration": {
              "type": "integer",
              "minimum": 1,
              "maximum": 3600
            }
          },
          "additionalProperties": false,
          "required": ["name"],
          "oneOf": [
            {
              "properties": {"action": {"enum": ["block-ip"]}},
              "required": ["name","category","block_ip_track_by","block_ip_duration"]
            },
            {
              "properties": {"action": {"enum": ["default","allow","alert","drop",
                "reset-client","reset-server","reset-both"]}}
            }
          ]
        }
      },
      "exception": {
        "type": "array",
        "items": {
          "type": "object",
          "properties": {
            "name": {
              "$ref": "#/$defs/naming"
            },
            "packet_capture": {
              "$ref": "#/$defs/capture_settings"
            },
            "action": {
              "$ref": "#/$defs/actions_rule_except"
            },
            "block_ip_track_by": {
              "type": "string",
              "enum": ["source","source-and-destination"]
            },
            "block_ip_duration": {
              "type": "integer",
              "minimum": 1,
              "maximum": 3600
            },
            "exempt_ips": {
              "type": "array",
              "items": {
                "type": "string",
                "pattern": "^[0-9./a-z:]+$",
                "maxLength": 39
              },
              "uniqueItems": true
            }
          },
          "additionalProperties": false,
          "required": ["name"],
          "oneOf": [
            {
              "properties": {"action": {"enum": ["block-ip"]}},
              "required": ["name","category","block_ip_track_by","block_ip_duration"]
            },
            {
              "properties": {"action": {"enum": ["default","allow","alert","drop",
                "reset-client","reset-server","reset-both"]}}
            }
          ]
        }
      },
      "additionalItems": false
    },
    "additionalProperties": false,
    "required": ["name"],
    "dependencies": {
      "device_group": {
        "not": {
          "required": ["vsys"]
        }
      },
      "vsys": {
        "not": {
          "required": ["device_group"]
        }
      }
    }
  },
  "uniqueItems": true,
  "additionalItems": false,

  "$defs": {
    "naming": {
      "type": "string",
      "maxLength": 31,
      "pattern": "^[a-zA-Z0-9_.\\s-]+$"
    },
    "actions_dns_botnet": {
      "type": "string",
      "enum": ["default","allow","alert","block","sinkhole"],
      "default": "default"
    },
    "actions_rule_except": {
      "type": "string",
      "enum": ["default","allow","alert","drop","block-ip","reset-client","reset-server","reset-both"],
      "default": "default"
    },
    "capture_settings": {
       "type": "string",
        "enum": ["disable","single-packet","extended-capture"],
        "default": "disable"
    },
    "categories": {
      "type": "string",
      "default": "any",
      "enum": ["adware","any","autogen","backdoor","botnet","browser-hijack", "command-and-control",
        "cryptominer","data-theft","dns","dns-benign", "dns-c2","dns-ddns","dns-grayware","dns-malware",
        "dns-new-domain","dns-parked","dns-phishing","dns-proxy","dns-security","dns-wildfire",
        "domain-edl","downloader","fraud","hacktool","keylogger","net-worm", "p2p-communication",
        "phishing-kit","post-exploitation","spyware","tls-fingerprint","webshell"]
    }
  },
  "additionalProperties": false
}

=== sarah-blazic/terraform-panos-policy-as-code/examples/basic_policy/iron_skillet/spyware.json
[
  {
    "name": "Outbound-AS",
    "botnet_list": [
      {
        "name": "default-paloalto-dns",
        "action": "sinkhole",
        "packet_capture": "single-packet"
      }
    ],
    "dns_category": [
      {
        "name": "pan-dns-sec-benign",
        "log_level": "default",
        "action": "default",
        "packet_capture": "disable"
      },
      {
        "name": "pan-dns-sec-cc",
        "log_level": "default",
        "action": "sinkhole",
        "packet_capture": "single-packet"
      },
      {
        "name": "pan-dns-sec-ddns",
        "log_level": "default",
        "action": "default",
        "packet_capture": "single-packet"
      },
      {
        "name": "pan-dns-sec-grayware",
        "log_level":"default",
        "action":"sinkhole",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-malware",
        "log_level":"default",
        "action":"sinkhole",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-parked",
        "log_level":"default",
        "action":"default",
        "packet_capture":"disable"
      },
      {
        "name":"pan-dns-sec-phishing",
        "log_level":"default",
        "action":"sinkhole",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-proxy",
        "log_level":"default",
        "action":"sinkhole",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-recent",
        "log_level":"default",
        "action":"default",
        "packet_capture":"single-packet"
      }
    ],
    "sinkhole_ipv4_address": "72.5.65.111",
    "sinkhole_ipv6_address":"2600:5200::1",
    "rule":
    [
      {
        "name": "Block-Critical-High-Medium",
        "action": "reset-both",
        "severities": ["critical","high","medium"],
        "threat_name": "any",
        "category": "any",
        "packet_capture": "single-packet"
      },
      {
        "name": "Default-Low-Info",
        "action": "default",
        "severities":["low","informational"],
        "threat_name": "any",
        "category":"any",
        "packet_capture":"disable"
      }
    ]
  },
  {
    "name": "Inbound-AS",
    "botnet_list": [
      {
        "name": "default-paloalto-dns",
        "action": "sinkhole",
        "packet_capture": "single-packet"
      }
    ],
    "dns_category": [
      {
        "name": "pan-dns-sec-benign",
        "log_level": "default",
        "action": "default",
        "packet_capture": "disable"
      },
      {
        "name": "pan-dns-sec-cc",
        "log_level": "default",
        "action": "sinkhole",
        "packet_capture": "single-packet"
      },
      {
        "name": "pan-dns-sec-ddns",
        "log_level": "default",
        "action": "default",
        "packet_capture": "single-packet"
      },
      {
        "name": "pan-dns-sec-grayware",
        "log_level":"default",
        "action":"sinkhole",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-malware",
        "log_level":"default",
        "action":"sinkhole",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-parked",
        "log_level":"default",
        "action":"default",
        "packet_capture":"disable"
      },
      {
        "name":"pan-dns-sec-phishing",
        "log_level":"default",
        "action":"sinkhole",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-proxy",
        "log_level":"default",
        "action":"sinkhole",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-recent",
        "log_level":"default",
        "action":"default",
        "packet_capture":"single-packet"
      }
    ],
    "sinkhole_ipv4_address": "72.5.65.111",
    "sinkhole_ipv6_address":"2600:5200::1",
    "rule":
    [
      {
        "name": "Block-Critical-High-Medium",
        "action": "reset-both",
        "severities": ["critical","high","medium"],
        "threat_name": "any",
        "category": "any",
        "packet_capture": "single-packet"
      },
      {
        "name": "Default-Low-Info",
        "action": "default",
        "severities":["low","informational"],
        "threat_name": "any",
        "category":"any",
        "packet_capture":"disable"
      }
    ]
  },
  {
    "name":"Internal-AS",
    "botnet_list": [
      {
        "name": "default-paloalto-dns",
        "action": "sinkhole",
        "packet_capture": "single-packet"
      }
    ],
    "dns_category": [
      {
        "name": "pan-dns-sec-benign",
        "log_level": "default",
        "action": "default",
        "packet_capture": "disable"
      },
      {
        "name": "pan-dns-sec-cc",
        "log_level": "default",
        "action": "sinkhole",
        "packet_capture": "single-packet"
      },
      {
        "name": "pan-dns-sec-ddns",
        "log_level": "default",
        "action": "default",
        "packet_capture": "single-packet"
      },
      {
        "name": "pan-dns-sec-grayware",
        "log_level":"default",
        "action":"sinkhole",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-malware",
        "log_level":"default",
        "action":"sinkhole",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-parked",
        "log_level":"default",
        "action":"default",
        "packet_capture":"disable"
      },
      {
        "name":"pan-dns-sec-phishing",
        "log_level":"default",
        "action":"sinkhole",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-proxy",
        "log_level":"default",
        "action":"sinkhole",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-recent",
        "log_level":"default",
        "action":"default",
        "packet_capture":"single-packet"
      }
    ],
    "sinkhole_ipv4_address": "72.5.65.111",
    "sinkhole_ipv6_address":"2600:5200::1",
    "rule":
    [
      {
        "name": "Block-Critical-High",
        "action": "reset-both",
        "severities": ["critical","high"],
        "threat_name": "any",
        "category": "any",
        "packet_capture": "single-packet"
      },
      {
        "name": "Default-Medium-Low-Info",
        "action": "default",
        "severities":["medium","low","informational"],
        "threat_name": "any",
        "category":"any",
        "packet_capture":"disable"
      }
    ]
  },
  {
    "name":"Alert-Only-AS",
    "botnet_list": [
      {
        "name": "default-paloalto-dns",
        "action": "alert",
        "packet_capture": "single-packet"
      }
    ],
    "dns_category": [
      {
        "name": "pan-dns-sec-benign",
        "log_level": "default",
        "action": "allow",
        "packet_capture": "disable"
      },
      {
        "name": "pan-dns-sec-cc",
        "log_level": "default",
        "action": "allow",
        "packet_capture": "single-packet"
      },
      {
        "name": "pan-dns-sec-ddns",
        "log_level": "default",
        "action": "allow",
        "packet_capture": "single-packet"
      },
      {
        "name": "pan-dns-sec-grayware",
        "log_level":"default",
        "action":"allow",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-malware",
        "log_level":"default",
        "action":"allow",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-parked",
        "log_level":"default",
        "action":"allow",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-phishing",
        "log_level":"default",
        "action":"allow",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-proxy",
        "log_level":"default",
        "action":"allow",
        "packet_capture":"single-packet"
      },
      {
        "name":"pan-dns-sec-recent",
        "log_level":"default",
        "action":"allow",
        "packet_capture":"single-packet"
      }
    ],
    "sinkhole_ipv4_address": "72.5.65.111",
    "sinkhole_ipv6_address":"2600:5200::1",
    "rule":
    [
      {
        "name": "Alert-All",
        "action": "alert",
        "severities": ["any"],
        "threat_name": "any",
        "category": "any",
        "packet_capture": "disable"
      }
    ]
  },
  {
    "name":"Exception-AS",
    "description":"Used for exception cases not part of the recommended practice",
    "botnet_list": [
      {
        "name": "default-paloalto-dns",
        "action": "sinkhole",
        "packet_capture": "single-packet"
      }
    ],
    "dns_category": [
      {
        "name": "pan-dns-sec-benign",
        "log_level": "default",
        "action": "default",
        "packet_capture": "disable"
      },
      {
        "name": "pan-dns-sec-cc",
        "log_level": "default",
        "action": "default",
        "packet_capture": "disable"
      },
      {
        "name": "pan-dns-sec-ddns",
        "log_level": "default",
        "action": "default",
        "packet_capture": "disable"
      },
      {
        "name": "pan-dns-sec-grayware",
        "log_level":"default",
        "action":"default",
        "packet_capture":"disable"
      },
      {
        "name":"pan-dns-sec-malware",
        "log_level":"default",
        "action":"default",
        "packet_capture":"disable"
      },
      {
        "name":"pan-dns-sec-parked",
        "log_level":"default",
        "action":"default",
        "packet_capture":"disable"
      },
      {
        "name":"pan-dns-sec-phishing",
        "log_level":"default",
        "action":"default",
        "packet_capture":"disable"
      },
      {
        "name":"pan-dns-sec-proxy",
        "log_level":"default",
        "action":"default",
        "packet_capture":"disable"
      },
      {
        "name":"pan-dns-sec-recent",
